import React, { useEffect, useState } from 'react';
import { BicycleSpot, RegisteredBicycle } from '../types';
import { Clock3, ClipboardList, ArrowRight, MapPinned, Bike, AlertTriangle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { getBikeReevaluationInfo } from '../utils/reevaluation';
import { getBikeFallbackPhoto } from '../utils/offlineBikes';

type TaskTopic = 'reevaluation' | 'queue' | 'irregularities';
type IrregularityRecord = { id: string; request_type: 'ocorrencia' | 'regularizacao'; resident_name: string; apartment: string; block: string; severity: 'normal' | 'attention' | 'urgent'; notes: string | null; };

export function TasksHub({ bikes, spots, dueCount, condominiumId, onTabChange, onOpenTask }: { bikes: RegisteredBicycle[]; spots: BicycleSpot[]; dueCount: number; condominiumId: string | null; onTabChange: (tab: 'dashboard' | 'map' | 'history' | 'bikes' | 'requests' | 'tasks') => void; onOpenTask: (focus: 'reevaluation' | 'queue' | 'irregularities') => void }) {
  const [selectedTopic, setSelectedTopic] = useState<TaskTopic>('reevaluation');
  const [irregularities, setIrregularities] = useState<IrregularityRecord[]>([]);
  useEffect(() => {
    if (!supabase || !condominiumId) { setIrregularities([]); return; }
    void supabase.from('spot_requests').select('id, request_type, resident_name, apartment, block, severity, notes').eq('condominium_id', condominiumId).in('status', ['pending', 'waiting_list']).in('request_type', ['ocorrencia', 'regularizacao']).order('created_at', { ascending: true }).then(({ data }) => setIrregularities((data || []) as IrregularityRecord[]));
  }, [condominiumId]);
  const awaitingSpot = bikes.filter((bike) => !bike.spotNumber).length;
  const awaitingBikes = bikes.filter((bike) => !bike.spotNumber);
  const dueBikes = bikes.filter((bike) => getBikeReevaluationInfo(bike).isDue);
  const isFirstSetup = spots.length === 0 || bikes.length === 0;
  return <div className="tasks-hub space-y-4">
    {isFirstSetup && <section className="rounded-2xl border border-orange-200 bg-[#fffaf2] p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#e87c0b]">Primeira configuração</p><h2 className="mt-1 text-base font-black text-[#0d1733]">Comece pelo essencial</h2><div className="mt-3 grid gap-2 sm:grid-cols-3"><button type="button" onClick={() => onTabChange('map')} className="rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-bold text-slate-700 transition hover:border-orange-300 hover:bg-orange-50"><MapPinned className="mb-2 h-4 w-4 text-[#e87c0b]" />1. Configure a planta</button><button type="button" onClick={() => onTabChange('bikes')} className="rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-bold text-slate-700 transition hover:border-orange-300 hover:bg-orange-50"><Bike className="mb-2 h-4 w-4 text-[#e87c0b]" />2. Cadastre bicicletas</button><button type="button" onClick={() => onTabChange('map')} className="rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-bold text-slate-700 transition hover:border-orange-300 hover:bg-orange-50"><ClipboardList className="mb-2 h-4 w-4 text-[#e87c0b]" />3. Vincule as vagas</button></div></section>}
    <section className="grid gap-4 lg:grid-cols-3">
      <article className={`rounded-2xl border bg-white p-5 shadow-sm transition ${selectedTopic === 'reevaluation' ? 'border-amber-400 ring-2 ring-amber-100' : 'border-amber-200'}`}><div className="flex items-start justify-between gap-3"><div><span className="inline-flex rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-800">REAVALIAÇÃO</span><h2 className="mt-3 text-lg font-black text-[#0d1733]">{dueCount} bicicleta{dueCount === 1 ? '' : 's'} para reavaliar</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">Revise vínculo do morador e condição da bicicleta antes de manter a concessão.</p></div><Clock3 className="h-6 w-6 text-amber-500" /></div><button type="button" onClick={() => setSelectedTopic('reevaluation')} className="mt-5 inline-flex items-center gap-1.5 text-xs font-black text-[#b96500]">Ver nesta tela <ArrowRight className="h-3.5 w-3.5" /></button></article>
      <article className={`rounded-2xl border bg-white p-5 shadow-sm transition ${selectedTopic === 'queue' ? 'border-emerald-400 ring-2 ring-emerald-100' : 'border-emerald-200'}`}><div className="flex items-start justify-between gap-3"><div><span className="inline-flex rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-800">FILA DE VAGAS</span><h2 className="mt-3 text-lg font-black text-[#0d1733]">{awaitingSpot} aguardando vaga</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">Consulte a fila, aprove solicitações e vincule vagas livres quando disponíveis.</p></div><ClipboardList className="h-6 w-6 text-emerald-600" /></div><button type="button" onClick={() => setSelectedTopic('queue')} className="mt-5 inline-flex items-center gap-1.5 text-xs font-black text-emerald-700">Ver nesta tela <ArrowRight className="h-3.5 w-3.5" /></button></article>
      <article className={`rounded-2xl border bg-white p-5 shadow-sm transition ${selectedTopic === 'irregularities' ? 'border-rose-400 ring-2 ring-rose-100' : 'border-rose-200'}`}><div className="flex items-start justify-between gap-3"><div><span className="inline-flex rounded-full bg-rose-50 px-2 py-1 text-[10px] font-black text-rose-800">IRREGULARIDADES</span><h2 className="mt-3 text-lg font-black text-[#0d1733]">{irregularities.length} em acompanhamento</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">Ocorrências e regularizações abertas que precisam de uma ação do síndico.</p></div><AlertTriangle className="h-6 w-6 text-rose-600" /></div><button type="button" onClick={() => setSelectedTopic('irregularities')} className="mt-5 inline-flex items-center gap-1.5 text-xs font-black text-rose-700">Ver nesta tela <ArrowRight className="h-3.5 w-3.5" /></button></article>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      {selectedTopic === 'reevaluation' && <><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-amber-700">Reavaliações pendentes</span><h2 className="mt-1 text-lg font-black text-[#0d1733]">Bicicletas para revisar</h2><p className="mt-1 text-xs text-slate-500">Priorize o vínculo do morador e as condições de conservação.</p></div><button type="button" onClick={() => onOpenTask('reevaluation')} className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-black text-amber-800">Abrir área completa</button></div><div className="mt-4 space-y-2">{dueBikes.slice(0, 4).map((bike, index) => <div key={bike.id} className="flex items-center gap-3 rounded-xl border border-amber-100 bg-amber-50/50 p-3"><img src={bike.photoUrl} alt="" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = getBikeFallbackPhoto(index); }} className="h-10 w-10 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[#0d1733]">{bike.residentName}</p><p className="mt-0.5 text-[10px] text-slate-600">Apto {bike.apartment}{bike.block ? ` · ${bike.block}` : ''} · {bike.spotNumber || 'Sem vaga'}</p></div><Clock3 className="h-4 w-4 text-amber-500" /></div>)}{dueBikes.length === 0 && <EmptyTopic label="Nenhuma reavaliação pendente." tone="emerald" />}</div></>}
      {selectedTopic === 'queue' && <><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-emerald-700">Fila de vagas</span><h2 className="mt-1 text-lg font-black text-[#0d1733]">Bicicletas aguardando vaga</h2><p className="mt-1 text-xs text-slate-500">Use a fila completa para escolher e atribuir uma vaga disponível.</p></div><button type="button" onClick={() => onOpenTask('queue')} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-800">Abrir fila completa</button></div><div className="mt-4 space-y-2">{awaitingBikes.slice(0, 4).map((bike, index) => <div key={bike.id} className="flex items-center gap-3 rounded-xl border border-emerald-100 bg-emerald-50/50 p-3"><img src={bike.photoUrl} alt="" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = getBikeFallbackPhoto(index); }} className="h-10 w-10 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[#0d1733]">{bike.residentName}</p><p className="mt-0.5 text-[10px] text-slate-600">Apto {bike.apartment}{bike.block ? ` · ${bike.block}` : ''}</p></div><MapPinned className="h-4 w-4 text-emerald-600" /></div>)}{awaitingBikes.length === 0 && <EmptyTopic label="Nenhuma bicicleta aguarda vaga." tone="emerald" />}</div></>}
      {selectedTopic === 'irregularities' && <><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-rose-700">Irregularidades</span><h2 className="mt-1 text-lg font-black text-[#0d1733]">Ocorrências e regularizações</h2><p className="mt-1 text-xs text-slate-500">Registros que exigem acompanhamento do síndico, sem alterar vagas automaticamente.</p></div><button type="button" onClick={() => onOpenTask('irregularities')} className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-black text-rose-800">Abrir registros</button></div><div className="mt-4 space-y-2">{irregularities.slice(0, 4).map((record) => <div key={record.id} className="flex items-center gap-3 rounded-xl border border-rose-100 bg-rose-50/50 p-3"><AlertTriangle className="h-4 w-4 shrink-0 text-rose-600" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[#0d1733]">{record.request_type === 'ocorrencia' ? 'Ocorrência' : 'Regularização'} · {record.resident_name}</p><p className="mt-0.5 truncate text-[10px] text-slate-600">Apto {record.apartment}{record.block ? ` · ${record.block}` : ''}{record.notes ? ` · ${record.notes}` : ''}</p></div><span className={`rounded px-2 py-1 text-[9px] font-black ${record.severity === 'urgent' ? 'bg-rose-100 text-rose-700' : record.severity === 'attention' ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-600'}`}>{record.severity === 'urgent' ? 'Urgente' : record.severity === 'attention' ? 'Atenção' : 'Normal'}</span></div>)}{irregularities.length === 0 && <EmptyTopic label="Nenhuma irregularidade em acompanhamento." tone="emerald" />}</div></>}
    </section>
  </div>;
}

function EmptyTopic({ label, tone }: { label: string; tone: 'emerald' | 'slate' }) { return <div className={`rounded-xl border border-dashed p-5 text-center text-xs font-bold ${tone === 'emerald' ? 'border-emerald-200 bg-emerald-50/50 text-emerald-800' : 'border-slate-200 text-slate-500'}`}>{label}</div>; }
