import React, { useEffect, useRef, useState } from 'react';
import { BicycleSpot, RegisteredBicycle } from '../types';
import { Clock3, ClipboardList, ArrowRight, MapPinned, Bike, AlertTriangle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { getBikeReevaluationInfo } from '../utils/reevaluation';
import { getBikeFallbackPhoto } from '../utils/offlineBikes';

export type TaskTopic = 'reevaluation' | 'queue' | 'irregularities';
type IrregularityRecord = { id: string; request_type: 'ocorrencia' | 'regularizacao'; resident_name: string; apartment: string; block: string; severity: 'normal' | 'attention' | 'urgent'; notes: string | null; };

export function TasksHub({ bikes, spots, dueCount, condominiumId, initialTopic, onTopicChange, onTabChange, onOpenTask, onStartReevaluation, onAssignSpot }: { bikes: RegisteredBicycle[]; spots: BicycleSpot[]; dueCount: number; condominiumId: string | null; initialTopic: TaskTopic; onTopicChange: (topic: TaskTopic) => void; onTabChange: (tab: 'dashboard' | 'map' | 'history' | 'bikes' | 'requests' | 'tasks') => void; onOpenTask: (focus: TaskTopic) => void; onStartReevaluation: (bike: RegisteredBicycle) => void; onAssignSpot: (bike: RegisteredBicycle) => void }) {
  const [selectedTopic, setSelectedTopic] = useState<TaskTopic>(initialTopic);
  const [irregularities, setIrregularities] = useState<IrregularityRecord[]>([]);
  const detailPanelRef = useRef<HTMLElement>(null);
  const selectTopic = (topic: TaskTopic) => {
    setSelectedTopic(topic);
    onTopicChange(topic);
    const reduceMotion = window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
    window.setTimeout(() => detailPanelRef.current?.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'start' }), 80);
  };
  useEffect(() => setSelectedTopic(initialTopic), [initialTopic]);
  useEffect(() => {
    if (!supabase || !condominiumId) { setIrregularities([]); return; }
    void supabase.from('spot_requests').select('id, request_type, resident_name, apartment, block, severity, notes').eq('condominium_id', condominiumId).in('status', ['pending', 'waiting_list']).in('request_type', ['ocorrencia', 'regularizacao']).order('created_at', { ascending: true }).then(({ data }) => setIrregularities((data || []) as IrregularityRecord[]));
  }, [condominiumId]);
  const awaitingSpot = bikes.filter((bike) => !bike.spotNumber).length;
  const awaitingBikes = bikes.filter((bike) => !bike.spotNumber);
  const dueBikes = bikes.filter((bike) => getBikeReevaluationInfo(bike).isDue);
  const isFirstSetup = spots.length === 0 || bikes.length === 0;
  return <div className="tasks-hub space-y-4">
    {isFirstSetup && <section className="rounded-2xl border border-orange-200 bg-[#fffaf2] p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#e87c0b]">Primeira configuração</p><h2 className="mt-1 text-base font-black text-[#0d1733]">Comece pelo essencial</h2><div className="mt-3 grid gap-2 sm:grid-cols-3"><button type="button" onClick={() => onTabChange('map')} className="rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-bold text-slate-700 transition hover:border-orange-300 hover:bg-orange-50"><MapPinned className="mb-2 h-4 w-4 text-[#e87c0b]" />1. Configure a planta</button><button type="button" onClick={() => onTabChange('bikes')} className="rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-bold text-slate-700 transition hover:border-orange-300 hover:bg-orange-50"><Bike className="mb-2 h-4 w-4 text-[#e87c0b]" />2. Cadastre bicicletas</button><button type="button" onClick={() => onTabChange('map')} className="rounded-xl border border-slate-200 bg-white p-3 text-left text-xs font-bold text-slate-700 transition hover:border-orange-300 hover:bg-orange-50"><ClipboardList className="mb-2 h-4 w-4 text-[#e87c0b]" />3. Vincule as vagas</button></div></section>}
    <section className="grid gap-4 lg:grid-cols-3">
      <TopicCard topic="reevaluation" activeTopic={selectedTopic} onSelect={selectTopic} label="REAVALIAÇÃO" title={`${dueCount} bicicleta${dueCount === 1 ? '' : 's'} para reavaliar`} description="Revise vínculo do morador e condição da bicicleta antes de manter a concessão." icon={<Clock3 className="h-6 w-6" />} tone="amber" />
      <TopicCard topic="queue" activeTopic={selectedTopic} onSelect={selectTopic} label="FILA DE VAGAS" title={`${awaitingSpot} aguardando vaga`} description="Consulte a fila, aprove solicitações e vincule vagas livres quando disponíveis." icon={<ClipboardList className="h-6 w-6" />} tone="emerald" />
      <TopicCard topic="irregularities" activeTopic={selectedTopic} onSelect={selectTopic} label="IRREGULARIDADES" title={`${irregularities.length} em acompanhamento`} description="Ocorrências e regularizações abertas que precisam de uma ação do síndico." icon={<AlertTriangle className="h-6 w-6" />} tone="rose" />
    </section>
    <section ref={detailPanelRef} className="task-topic-detail rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      {selectedTopic === 'reevaluation' && <><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-amber-700">Reavaliações pendentes</span><h2 className="mt-1 text-lg font-black text-[#0d1733]">Bicicletas para revisar</h2><p className="mt-1 text-xs text-slate-500">Priorize o vínculo do morador e as condições de conservação.</p></div><button type="button" onClick={() => onOpenTask('reevaluation')} className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-black text-amber-800">Abrir área completa</button></div><div className="mt-4 space-y-2">{dueBikes.slice(0, 4).map((bike, index) => <button key={bike.id} type="button" onClick={() => onStartReevaluation(bike)} className="flex w-full items-center gap-3 rounded-xl border border-amber-100 bg-amber-50/50 p-3 text-left transition hover:border-amber-300 hover:bg-amber-50"><img src={bike.photoUrl} alt="" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = getBikeFallbackPhoto(index); }} className="h-10 w-10 rounded-lg object-cover" /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-black text-[#0d1733]">{bike.residentName}</span><span className="mt-0.5 block text-[10px] text-slate-600">Apto {bike.apartment}{bike.block ? ` · ${bike.block}` : ''} · {bike.spotNumber || 'Sem vaga'}</span></span><span className="text-[10px] font-black text-amber-800">Reavaliar</span><Clock3 className="h-4 w-4 text-amber-500" /></button>)}{dueBikes.length === 0 && <EmptyTopic label="Nenhuma reavaliação pendente." tone="emerald" />}</div></>}
      {selectedTopic === 'queue' && <><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-emerald-700">Fila de vagas</span><h2 className="mt-1 text-lg font-black text-[#0d1733]">Bicicletas aguardando vaga</h2><p className="mt-1 text-xs text-slate-500">Use a fila completa para escolher e atribuir uma vaga disponível.</p></div><button type="button" onClick={() => onOpenTask('queue')} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-800">Abrir fila completa</button></div><div className="mt-4 space-y-2">{awaitingBikes.slice(0, 4).map((bike, index) => <button key={bike.id} type="button" onClick={() => onAssignSpot(bike)} className="flex w-full items-center gap-3 rounded-xl border border-emerald-100 bg-emerald-50/50 p-3 text-left transition hover:border-emerald-300 hover:bg-emerald-50"><img src={bike.photoUrl} alt="" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = getBikeFallbackPhoto(index); }} className="h-10 w-10 rounded-lg object-cover" /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-black text-[#0d1733]">{bike.residentName}</span><span className="mt-0.5 block text-[10px] text-slate-600">Apto {bike.apartment}{bike.block ? ` · ${bike.block}` : ''}</span></span><span className="text-[10px] font-black text-emerald-800">Escolher vaga</span><MapPinned className="h-4 w-4 text-emerald-600" /></button>)}{awaitingBikes.length === 0 && <EmptyTopic label="Nenhuma bicicleta aguarda vaga." tone="emerald" />}</div></>}
      {selectedTopic === 'irregularities' && <><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-rose-700">Irregularidades</span><h2 className="mt-1 text-lg font-black text-[#0d1733]">Ocorrências e regularizações</h2><p className="mt-1 text-xs text-slate-500">Registros que exigem acompanhamento do síndico, sem alterar vagas automaticamente.</p></div><button type="button" onClick={() => onOpenTask('irregularities')} className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-black text-rose-800">Abrir registros</button></div><div className="mt-4 space-y-2">{irregularities.slice(0, 4).map((record) => <div key={record.id} className="flex items-center gap-3 rounded-xl border border-rose-100 bg-rose-50/50 p-3"><AlertTriangle className="h-4 w-4 shrink-0 text-rose-600" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[#0d1733]">{record.request_type === 'ocorrencia' ? 'Ocorrência' : 'Regularização'} · {record.resident_name}</p><p className="mt-0.5 truncate text-[10px] text-slate-600">Apto {record.apartment}{record.block ? ` · ${record.block}` : ''}{record.notes ? ` · ${record.notes}` : ''}</p></div><span className={`rounded px-2 py-1 text-[9px] font-black ${record.severity === 'urgent' ? 'bg-rose-100 text-rose-700' : record.severity === 'attention' ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-600'}`}>{record.severity === 'urgent' ? 'Urgente' : record.severity === 'attention' ? 'Atenção' : 'Normal'}</span></div>)}{irregularities.length === 0 && <EmptyTopic label="Nenhuma irregularidade em acompanhamento." tone="emerald" />}</div></>}
    </section>
  </div>;
}

function EmptyTopic({ label, tone }: { label: string; tone: 'emerald' | 'slate' }) { return <div className={`rounded-xl border border-dashed p-5 text-center text-xs font-bold ${tone === 'emerald' ? 'border-emerald-200 bg-emerald-50/50 text-emerald-800' : 'border-slate-200 text-slate-500'}`}>{label}</div>; }

function TopicCard({ topic, activeTopic, onSelect, label, title, description, icon, tone }: { topic: TaskTopic; activeTopic: TaskTopic; onSelect: (topic: TaskTopic) => void; label: string; title: string; description: string; icon: React.ReactNode; tone: 'amber' | 'emerald' | 'rose' }) {
  const active = activeTopic === topic;
  const styles = {
    amber: { border: active ? 'border-amber-400 ring-2 ring-amber-100' : 'border-amber-200', tag: 'bg-amber-50 text-amber-800', icon: 'text-amber-500', action: 'text-[#b96500]' },
    emerald: { border: active ? 'border-emerald-400 ring-2 ring-emerald-100' : 'border-emerald-200', tag: 'bg-emerald-50 text-emerald-800', icon: 'text-emerald-600', action: 'text-emerald-700' },
    rose: { border: active ? 'border-rose-400 ring-2 ring-rose-100' : 'border-rose-200', tag: 'bg-rose-50 text-rose-800', icon: 'text-rose-600', action: 'text-rose-700' },
  }[tone];
  return <button type="button" onClick={() => onSelect(topic)} aria-pressed={active} className={`task-topic-card task-topic-card--${tone} ${active ? 'task-topic-card--active' : ''} rounded-2xl border bg-white p-5 text-left shadow-sm ${styles.border}`}><span className="flex items-start justify-between gap-3"><span><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-black ${styles.tag}`}>{label}</span><span className="mt-3 block text-lg font-black text-[#0d1733]">{title}</span><span className="mt-1 block text-xs leading-relaxed text-slate-500">{description}</span></span><span className={styles.icon}>{icon}</span></span><span className={`mt-5 inline-flex items-center gap-1.5 text-xs font-black ${styles.action}`}>{active ? 'Em exibição abaixo' : 'Ver nesta tela'} <ArrowRight className={`h-3.5 w-3.5 transition-transform duration-300 ${active ? 'translate-x-1' : ''}`} /></span></button>;
}
