import { RegisteredBicycle } from './types';
import { SAMPLE_BIKE_PHOTOS } from './mockData';

export const INITIAL_REGISTERED_BIKES: RegisteredBicycle[] = [
  {
    id: 'bike-01',
    brandModel: 'Trek Marlin 7',
    color: 'Azul Metálico',
    category: 'Mountain Bike',
    tagNumber: 'TAG-2024-001',
    serialNumber: 'TRK-7890-MTB',
    distinguishingFeatures: 'Cadeado em U reforçado no quadro, suporte caramanhola preto, refletor traseiro vermelho',
    notes: 'Bicicleta de uso esportivo nos finais de semana',
    photoUrl: SAMPLE_BIKE_PHOTOS[0],
    residentName: 'Carlos Eduardo Mendes',
    apartment: '402',
    block: 'Bloco A',
    residentPhone: '(11) 98452-1102',
    residentEmail: 'carlos.mendes@email.com',
    spotId: 'spot-01',
    spotNumber: 'S-01',
    registeredAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'bike-02',
    brandModel: 'Caloi City Tour Comp',
    color: 'Preto Fosco',
    category: 'Urbana',
    tagNumber: 'TAG-2024-018',
    serialNumber: 'CL-9021-CT',
    distinguishingFeatures: 'Bagageiro traseiro preto em alumínio, campainha cromada, farol dianteiro recarregável USB',
    notes: 'Moradora viajou a trabalho recentemente',
    photoUrl: SAMPLE_BIKE_PHOTOS[1],
    residentName: 'Fernanda Lima Rocha',
    apartment: '105',
    block: 'Bloco B',
    residentPhone: '(11) 97123-4567',
    spotId: 'spot-02',
    spotNumber: 'S-02',
    registeredAt: '2024-06-01T14:30:00Z',
  },
  {
    id: 'bike-05',
    brandModel: 'Sense Breeze E-Bike',
    color: 'Cinza Chumbo com detalhes azul celeste',
    category: 'Elétrica',
    tagNumber: 'TAG-2024-005',
    serialNumber: 'SNS-5520-EB',
    distinguishingFeatures: 'Bateria integrada no tubo inferior, display LCD no guidão, para-lamas dianteiro e traseiro pretos',
    notes: 'Bicicleta elétrica assistida com carregador original',
    photoUrl: SAMPLE_BIKE_PHOTOS[3],
    residentName: 'Juliana Paes Ribeiro',
    apartment: '501',
    block: 'Bloco A',
    residentPhone: '(11) 98877-6655',
    spotId: 'spot-05',
    spotNumber: 'S-05',
    registeredAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'bike-07',
    brandModel: 'Specialized Rockhopper 29',
    color: 'Vermelha e Preta',
    category: 'Mountain Bike',
    tagNumber: 'TAG-2024-007',
    serialNumber: 'SP-1104-RK',
    distinguishingFeatures: 'Suspensão dianteira RockShox preta, adesivo de trilha no tubo superior, pneus aro 29 cravudos',
    notes: 'Bicicleta de trilha, morador faz manutenção periódica',
    photoUrl: SAMPLE_BIKE_PHOTOS[4],
    residentName: 'Roberto Alencar Silveira',
    apartment: '204',
    block: 'Bloco B',
    residentPhone: '(11) 97654-3210',
    spotId: 'spot-07',
    spotNumber: 'S-07',
    registeredAt: '2024-04-20T16:00:00Z',
  },
  {
    id: 'bike-09',
    brandModel: 'Scott Scale 970',
    color: 'Amarela Neon e Preto',
    category: 'Mountain Bike',
    tagNumber: 'TAG-2024-009',
    serialNumber: 'SCT-970-YL',
    distinguishingFeatures: 'Manoplas ergonômicas amarelas, suporte articulado para celular no guidão, sem descanso lateral',
    notes: 'Quadro ultraleve em alumínio 6061',
    photoUrl: SAMPLE_BIKE_PHOTOS[5],
    residentName: 'Thiago Martins Bueno',
    apartment: '302',
    block: 'Bloco A',
    residentPhone: '(11) 99122-3344',
    spotId: 'spot-09',
    spotNumber: 'S-09',
    registeredAt: '2024-02-12T11:00:00Z',
  },
  {
    id: 'bike-11',
    brandModel: 'Dahon Mariner D8',
    color: 'Prata Metálico com detalhes azuis',
    category: 'Dobrável',
    tagNumber: 'TAG-2024-011',
    serialNumber: 'DH-8842-MB',
    distinguishingFeatures: 'Quadro dobrável com presilha de liberação rápida, aro 20, pedal retrátil em nylon',
    notes: 'Bicicleta dobrável usada para deslocamento diário até o metrô',
    photoUrl: SAMPLE_BIKE_PHOTOS[6],
    residentName: 'Mariana Costa e Silva',
    apartment: '102',
    block: 'Bloco A',
    residentPhone: '(11) 98233-4455',
    spotId: 'spot-11',
    spotNumber: 'S-11',
    registeredAt: '2024-05-18T08:30:00Z',
  },
  {
    id: 'bike-14',
    brandModel: 'Cannondale Topstone 3',
    color: 'Verde Oliva Fosco',
    category: 'Gravel',
    tagNumber: 'TAG-2024-014',
    serialNumber: 'CD-3049-TP',
    distinguishingFeatures: 'Guidão drop flare alargado, fita de guidão preta texturizada, bolsa triangular impermeável no quadro',
    notes: 'Gravel para asfalto e estradas de terra batida',
    photoUrl: SAMPLE_BIKE_PHOTOS[0],
    residentName: 'André Luiz Fonseca',
    apartment: '603',
    block: 'Bloco B',
    residentPhone: '(11) 97344-5566',
    spotId: 'spot-14',
    spotNumber: 'S-14',
    registeredAt: '2024-03-25T17:15:00Z',
  },
  {
    id: 'bike-17',
    brandModel: 'Caloi Andes Aro 26',
    color: 'Vermelha com detalhes brancos',
    category: 'Mountain Bike',
    tagNumber: 'TAG-2024-017',
    serialNumber: 'CL-6612-AD',
    distinguishingFeatures: 'Suspensão dianteira e traseira (full suspension), descanso lateral cromado, adesivos originais Caloi',
    notes: 'Bicicleta tradicional de passeio',
    photoUrl: SAMPLE_BIKE_PHOTOS[1],
    residentName: 'Beatriz Nogueira Dias',
    apartment: '401',
    block: 'Bloco B',
    residentPhone: '(11) 99455-6677',
    spotId: 'spot-17',
    spotNumber: 'S-17',
    registeredAt: '2024-07-02T13:40:00Z',
  },
  {
    id: 'bike-19',
    brandModel: 'Oggi Hacker Sport 29',
    color: 'Preto com Verde Claro',
    category: 'Mountain Bike',
    tagNumber: 'TAG-2024-019',
    serialNumber: 'OG-2911-HK',
    distinguishingFeatures: 'Freios a disco mecânicos, garrafa térmica verde presa ao suporte, protetor de corrente plástico preto',
    notes: 'Bicicleta de uso regular',
    photoUrl: SAMPLE_BIKE_PHOTOS[2],
    residentName: 'Gabriel Santoro Pires',
    apartment: '201',
    block: 'Bloco A',
    residentPhone: '(11) 98566-7788',
    spotId: 'spot-19',
    spotNumber: 'S-19',
    registeredAt: '2024-04-05T19:00:00Z',
  },
  {
    id: 'bike-21',
    brandModel: 'Houston Foxer Beach',
    color: 'Lilás Pastel',
    category: 'Urbana',
    tagNumber: 'TAG-2024-021',
    serialNumber: 'HST-4432-FX',
    distinguishingFeatures: 'Cestinha de vime marrom na frente, selim largo de molas acolchoado, campainha tipo campana retrô',
    notes: 'Bicicleta de passeio praiana',
    photoUrl: SAMPLE_BIKE_PHOTOS[3],
    residentName: 'Patrícia Helena Moreira',
    apartment: '304',
    block: 'Bloco B',
    residentPhone: '(11) 99677-8899',
    spotId: 'spot-21',
    spotNumber: 'S-21',
    registeredAt: '2024-06-12T15:20:00Z',
  },
  // Bicicletas cadastradas no condomínio que AINDA NÃO POSSUEM VAGA SUSPENSA ATRIBUÍDA
  // ou que podem ser encontradas soltas/abandonadas
  {
    id: 'bike-30',
    brandModel: 'Monark Barra Circular Clássica',
    color: 'Azul Escuro com grafismo dourado',
    category: 'Urbana',
    tagNumber: 'TAG-2024-030',
    serialNumber: 'MNK-1982-BC',
    distinguishingFeatures: 'Quadro circular clássico, cobre-corrente integral de metal azul, para-lamas largos e farol dínamos vintage',
    notes: 'Bicicleta pesada e histórica de família. Morador solicitou vaga no térreo.',
    photoUrl: SAMPLE_BIKE_PHOTOS[4],
    residentName: 'Bruno Guimarães',
    apartment: '103',
    block: 'Bloco B',
    residentPhone: '(11) 98112-9988',
    registeredAt: '2024-05-10T11:00:00Z',
  },
  {
    id: 'bike-31',
    brandModel: 'Caloi Vulcan 29',
    color: 'Laranja com Cinza',
    category: 'Mountain Bike',
    tagNumber: 'TAG-2024-031',
    serialNumber: 'CL-2944-VC',
    distinguishingFeatures: 'Adesivo da bandeira do Brasil no quadro, aro 29 aero preto, pneu dianteiro com pouca pressão e corrente sem óleo',
    notes: 'Avistada recentemente encostada na rampa da garagem sem travar',
    photoUrl: SAMPLE_BIKE_PHOTOS[5],
    residentName: 'Rodrigo Valente',
    apartment: '305',
    block: 'Bloco A',
    residentPhone: '(11) 98990-4433',
    registeredAt: '2024-06-20T10:30:00Z',
  },
  {
    id: 'bike-32',
    brandModel: 'Caloi 10 Vintage Sport',
    color: 'Branca e Dourada',
    category: 'Speed / Road',
    tagNumber: 'TAG-2024-032',
    serialNumber: 'CL-1088-VT',
    distinguishingFeatures: 'Guidão drop de corrida com fita branca gasta, trocadores de marcha no quadro (alavanca de fricção), pedais com firma-pé',
    notes: 'Proprietário aguardando disponibilidade de gancho suspensório',
    photoUrl: SAMPLE_BIKE_PHOTOS[6],
    residentName: 'Camila Torres Rezende',
    apartment: '502',
    block: 'Bloco B',
    residentPhone: '(11) 97889-1122',
    registeredAt: '2024-07-15T14:10:00Z',
  },
  {
    id: 'bike-33',
    brandModel: 'Houston Nina Aro 16',
    color: 'Rosa e Roxa',
    category: 'Infantil',
    tagNumber: 'TAG-2024-033',
    serialNumber: 'HST-1602-NN',
    distinguishingFeatures: 'Bicicleta infantil aro 16, rodinhas laterais removíveis de apoio, cestinha frontal plástica rosa com adesivos',
    notes: 'Bicicleta da filha de 5 anos da moradora',
    photoUrl: SAMPLE_BIKE_PHOTOS[7],
    residentName: 'Larissa Fagundes',
    apartment: '203',
    block: 'Bloco A',
    residentPhone: '(11) 99778-5544',
    registeredAt: '2024-08-01T16:00:00Z',
  },
];
