import { BicycleSpot, SystemConfig, UsageLog } from './types';
import { OFFLINE_SAMPLE_PHOTOS } from './utils/offlineBikes';

// Planta-base do ambiente de demonstração. Ela mantém o mapa compreensível em
// dispositivos novos, sem substituir uma planta salva pela implantação técnica.
const DEMO_FLOOR_PLAN = {
  name: 'Planta geral do bicicletário',
  updatedAt: '2026-09-12T00:00:00.000Z',
  modules: [
    { id: 'demo-entrance', name: 'Entrada', kind: 'entrance' as const, x: 4, y: 6, width: 20, height: 11, spotCapacity: 0 },
    { id: 'demo-corridor-left', name: 'Circulação lateral', kind: 'corridor' as const, flowDirection: 'vertical' as const, x: 4, y: 21, width: 18, height: 62, spotCapacity: 0 },
    { id: 'demo-module-c', name: 'Trilho suspenso leste', kind: 'bike_module' as const, x: 30, y: 6, width: 64, height: 13, spotCapacity: 8, assignedSector: 'Setor C - Trilho Suspenso Leste' },
    { id: 'demo-corridor-top', name: 'Fluxo central', kind: 'corridor' as const, flowDirection: 'horizontal' as const, x: 27, y: 23, width: 68, height: 20, spotCapacity: 0 },
    { id: 'demo-module-b', name: 'Parede sul', kind: 'bike_module' as const, x: 30, y: 47, width: 64, height: 13, spotCapacity: 8, assignedSector: 'Setor B - Parede Sul' },
    { id: 'demo-corridor-bottom', name: 'Fluxo inferior', kind: 'corridor' as const, flowDirection: 'horizontal' as const, x: 27, y: 64, width: 68, height: 19, spotCapacity: 0 },
    { id: 'demo-module-a', name: 'Parede norte', kind: 'bike_module' as const, x: 6, y: 87, width: 88, height: 10, spotCapacity: 8, assignedSector: 'Setor A - Parede Norte' },
  ],
};

export const DEFAULT_CONFIG: SystemConfig = {
  condominiumName: 'Condomínio Horizonte – Demonstração',
  condominiumCode: 'DEMO-HORIZONTE-250',
  condominiumCity: 'São Paulo/SP',
  managerName: 'Administração do Condomínio',
  deploymentNotes: 'Ambiente demonstrativo Nobrutec: 3 blocos e 250 apartamentos.',
  idleDaysThreshold: 30, // 30 dias sem uso gera alerta de ociosidade
  expiryWarningDays: 15,
  totalSuspendedHooks: 24,
  sectorFloorPlans: {
    'planta-geral': DEMO_FLOOR_PLAN,
  },
};

// Imagens vetoriais realistas em SVG Data URI para funcionamento 100% offline local
export const SAMPLE_BIKE_PHOTOS = OFFLINE_SAMPLE_PHOTOS;

// Helper to compute dates relative to the current day for a realistic demo.
const baseDate = new Date();
const daysAgo = (days: number) => {
  const d = new Date(baseDate.getTime() - days * 24 * 60 * 60 * 1000);
  return d.toISOString();
};
const daysFromNow = (days: number) => {
  const d = new Date(baseDate.getTime() + days * 24 * 60 * 60 * 1000);
  return d.toISOString();
};

export const INITIAL_SPOTS: BicycleSpot[] = [
  // SETOR A - PAREDE NORTE (Ganchos Verticais)
  {
    id: 'spot-01',
    spotNumber: 'S-01',
    sector: 'Setor A - Parede Norte',
    wallPosition: 1,
    maxWeightKg: 28,
    hookType: 'Gancho Vertical c/ Apoio de Pneu',
    qrCodeValue: 'COND-BIKE-S01',
    lastUsageDate: daysAgo(2), // Usada há 2 dias -> Ativa em dia
    currentAllocation: {
      id: 'alloc-01',
      spotId: 'spot-01',
      apartment: '402',
      block: 'Bloco A',
      residentName: 'Carlos Eduardo Mendes',
      residentPhone: '(11) 98452-1102',
      residentEmail: 'carlos.mendes@email.com',
      concessionType: 'vitalicio',
      startDate: daysAgo(180),
      bicycle: {
        brandModel: 'Trek Marlin 7',
        color: 'Azul Metálico',
        category: 'Mountain Bike',
        tagNumber: 'TAG-2024-001',
        notes: 'Bicicleta com cadeado em U reforçado no gancho',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[0],
      allocatedAt: daysAgo(180),
    },
  },
  {
    id: 'spot-02',
    spotNumber: 'S-02',
    sector: 'Setor A - Parede Norte',
    wallPosition: 2,
    maxWeightKg: 28,
    hookType: 'Gancho Vertical c/ Apoio de Pneu',
    qrCodeValue: 'COND-BIKE-S02',
    lastUsageDate: daysAgo(42), // 42 dias sem uso! -> OCIOSA (limite padrão é 30 dias)
    currentAllocation: {
      id: 'alloc-02',
      spotId: 'spot-02',
      apartment: '105',
      block: 'Bloco B',
      residentName: 'Fernanda Lima Rocha',
      residentPhone: '(11) 97123-4567',
      concessionType: 'determinado',
      startDate: daysAgo(90),
      endDate: daysFromNow(90), // Vence em 90 dias
      bicycle: {
        brandModel: 'Caloi City Tour Comp',
        color: 'Preto Fosco',
        category: 'Urbana',
        tagNumber: 'TAG-2024-018',
        notes: 'Moradora viajou a trabalho no último mês',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[1],
      allocatedAt: daysAgo(90),
    },
  },
  {
    id: 'spot-03',
    spotNumber: 'S-03',
    sector: 'Setor A - Parede Norte',
    wallPosition: 3,
    maxWeightKg: 30,
    hookType: 'Gancho Vertical c/ Apoio de Pneu',
    qrCodeValue: 'COND-BIKE-S03',
    // DISPONÍVEL
  },
  {
    id: 'spot-04',
    spotNumber: 'S-04',
    sector: 'Setor A - Parede Norte',
    wallPosition: 4,
    maxWeightKg: 28,
    hookType: 'Gancho Vertical c/ Apoio de Pneu',
    qrCodeValue: 'COND-BIKE-S04',
    lastUsageDate: daysAgo(5),
    currentAllocation: {
      id: 'alloc-04',
      spotId: 'spot-04',
      apartment: '804',
      block: 'Bloco A',
      residentName: 'Rodrigo Silveira',
      residentPhone: '(11) 99887-3321',
      concessionType: 'determinado',
      startDate: daysAgo(350),
      endDate: daysAgo(5), // EXPIRADA há 5 dias! -> Alerta de Vencimento
      bicycle: {
        brandModel: 'Specialized Allez E5',
        color: 'Vermelho e Branco',
        category: 'Speed / Road',
        tagNumber: 'TAG-2023-044',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[2],
      allocatedAt: daysAgo(350),
    },
  },
  {
    id: 'spot-05',
    spotNumber: 'S-05',
    sector: 'Setor A - Parede Norte',
    wallPosition: 5,
    maxWeightKg: 35,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S05',
    lastUsageDate: daysAgo(1),
    currentAllocation: {
      id: 'alloc-05',
      spotId: 'spot-05',
      apartment: '301',
      block: 'Bloco C',
      residentName: 'Mariana Duarte Souza',
      residentPhone: '(11) 98765-4321',
      concessionType: 'vitalicio',
      startDate: daysAgo(210),
      bicycle: {
        brandModel: 'Sense Breeze E-Bike',
        color: 'Cinza Nardo',
        category: 'Elétrica',
        tagNumber: 'TAG-2024-009',
        notes: 'Bateria removível sempre guardada no apartamento',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[3],
      allocatedAt: daysAgo(210),
    },
  },
  {
    id: 'spot-06',
    spotNumber: 'S-06',
    sector: 'Setor A - Parede Norte',
    wallPosition: 6,
    maxWeightKg: 28,
    hookType: 'Gancho Vertical c/ Apoio de Pneu',
    qrCodeValue: 'COND-BIKE-S06',
    // DISPONÍVEL
  },
  {
    id: 'spot-07',
    spotNumber: 'S-07',
    sector: 'Setor A - Parede Norte',
    wallPosition: 7,
    maxWeightKg: 28,
    hookType: 'Gancho Vertical c/ Apoio de Pneu',
    qrCodeValue: 'COND-BIKE-S07',
    lastUsageDate: daysAgo(12),
    currentAllocation: {
      id: 'alloc-07',
      spotId: 'spot-07',
      apartment: '603',
      block: 'Bloco B',
      residentName: 'Thiago Alcantara',
      residentPhone: '(11) 97451-2299',
      concessionType: 'determinado',
      startDate: daysAgo(60),
      endDate: daysFromNow(8), // Vence em 8 dias -> Alerta de Vencendo
      bicycle: {
        brandModel: 'Cannondale Trail 5',
        color: 'Verde Oliva',
        category: 'Mountain Bike',
        tagNumber: 'TAG-2024-055',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[4],
      allocatedAt: daysAgo(60),
    },
  },
  {
    id: 'spot-08',
    spotNumber: 'S-08',
    sector: 'Setor A - Parede Norte',
    wallPosition: 8,
    maxWeightKg: 28,
    hookType: 'Gancho Vertical c/ Apoio de Pneu',
    qrCodeValue: 'COND-BIKE-S08',
    // DISPONÍVEL
  },

  // SETOR B - PAREDE SUL (Ganchos Articulados)
  {
    id: 'spot-09',
    spotNumber: 'S-09',
    sector: 'Setor B - Parede Sul',
    wallPosition: 1,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S09',
    lastUsageDate: daysAgo(3),
    currentAllocation: {
      id: 'alloc-09',
      spotId: 'spot-09',
      apartment: '1202',
      block: 'Bloco A',
      residentName: 'Beatriz Martins Ramos',
      residentPhone: '(11) 98112-9900',
      concessionType: 'vitalicio',
      startDate: daysAgo(300),
      bicycle: {
        brandModel: 'Oggi Big Wheel 7.2',
        color: 'Grafite e Laranja',
        category: 'Mountain Bike',
        tagNumber: 'TAG-2023-012',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[5],
      allocatedAt: daysAgo(300),
    },
  },
  {
    id: 'spot-10',
    spotNumber: 'S-10',
    sector: 'Setor B - Parede Sul',
    wallPosition: 2,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S10',
    lastUsageDate: daysAgo(56), // 56 dias sem registro! -> OCIOSA CRÍTICA
    currentAllocation: {
      id: 'alloc-10',
      spotId: 'spot-10',
      apartment: '204',
      block: 'Bloco B',
      residentName: 'Guilherme Sampaio',
      residentPhone: '(11) 97722-1133',
      concessionType: 'vitalicio',
      startDate: daysAgo(400),
      bicycle: {
        brandModel: 'Monark Barra Circular Vintage',
        color: 'Azul Clássico',
        category: 'Urbana',
        tagNumber: 'TAG-2023-005',
        notes: 'Pneu traseiro aparenta estar murcho',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[6],
      allocatedAt: daysAgo(400),
    },
  },
  {
    id: 'spot-11',
    spotNumber: 'S-11',
    sector: 'Setor B - Parede Sul',
    wallPosition: 3,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S11',
    // DISPONÍVEL
  },
  {
    id: 'spot-12',
    spotNumber: 'S-12',
    sector: 'Setor B - Parede Sul',
    wallPosition: 4,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S12',
    lastUsageDate: daysAgo(7),
    currentAllocation: {
      id: 'alloc-12',
      spotId: 'spot-12',
      apartment: '501',
      block: 'Bloco A',
      residentName: 'Juliana Costa e Silva',
      residentPhone: '(11) 98344-5566',
      concessionType: 'determinado',
      startDate: daysAgo(45),
      endDate: daysFromNow(135),
      bicycle: {
        brandModel: 'Dahon Mariner D8 Dobrável',
        color: 'Prata Escovado',
        category: 'Dobrável',
        tagNumber: 'TAG-2024-031',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[7],
      allocatedAt: daysAgo(45),
    },
  },
  {
    id: 'spot-13',
    spotNumber: 'S-13',
    sector: 'Setor B - Parede Sul',
    wallPosition: 5,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S13',
    // DISPONÍVEL
  },
  {
    id: 'spot-14',
    spotNumber: 'S-14',
    sector: 'Setor B - Parede Sul',
    wallPosition: 6,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S14',
    lastUsageDate: daysAgo(4),
    currentAllocation: {
      id: 'alloc-14',
      spotId: 'spot-14',
      apartment: '903',
      block: 'Bloco C',
      residentName: 'Lucas Ferreira',
      residentPhone: '(11) 99123-0044',
      concessionType: 'vitalicio',
      startDate: daysAgo(120),
      bicycle: {
        brandModel: 'Scott Aspect 950',
        color: 'Laranja Flame',
        category: 'Mountain Bike',
        tagNumber: 'TAG-2024-067',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[0],
      allocatedAt: daysAgo(120),
    },
  },
  {
    id: 'spot-15',
    spotNumber: 'S-15',
    sector: 'Setor B - Parede Sul',
    wallPosition: 7,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S15',
    // DISPONÍVEL
  },
  {
    id: 'spot-16',
    spotNumber: 'S-16',
    sector: 'Setor B - Parede Sul',
    wallPosition: 8,
    maxWeightKg: 30,
    hookType: 'Suporte Articulado Giratório',
    qrCodeValue: 'COND-BIKE-S16',
    // DISPONÍVEL
  },

  // SETOR C - PAREDE LESTE (Ganchos de Teto / Trilho Suspenso)
  {
    id: 'spot-17',
    spotNumber: 'S-17',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 1,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S17',
    lastUsageDate: daysAgo(1),
    currentAllocation: {
      id: 'alloc-17',
      spotId: 'spot-17',
      apartment: '702',
      block: 'Bloco B',
      residentName: 'Patrícia Nogueira',
      residentPhone: '(11) 98877-6655',
      concessionType: 'determinado',
      startDate: daysAgo(15),
      endDate: daysFromNow(350),
      bicycle: {
        brandModel: 'Groove Rhythm Carbon',
        color: 'Preto e Amarelo Neon',
        category: 'Mountain Bike',
        tagNumber: 'TAG-2024-099',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[1],
      allocatedAt: daysAgo(15),
    },
  },
  {
    id: 'spot-18',
    spotNumber: 'S-18',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 2,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S18',
    // DISPONÍVEL
  },
  {
    id: 'spot-19',
    spotNumber: 'S-19',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 3,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S19',
    lastUsageDate: daysAgo(35), // 35 dias sem uso -> OCIOSA
    currentAllocation: {
      id: 'alloc-19',
      spotId: 'spot-19',
      apartment: '1104',
      block: 'Bloco A',
      residentName: 'Marcelo Rezende',
      residentPhone: '(11) 97334-8899',
      concessionType: 'vitalicio',
      startDate: daysAgo(500),
      bicycle: {
        brandModel: 'Trek Domane AL 2',
        color: 'Branco Pérola',
        category: 'Speed / Road',
        tagNumber: 'TAG-2023-019',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[2],
      allocatedAt: daysAgo(500),
    },
  },
  {
    id: 'spot-20',
    spotNumber: 'S-20',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 4,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S20',
    // DISPONÍVEL
  },
  {
    id: 'spot-21',
    spotNumber: 'S-21',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 5,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S21',
    lastUsageDate: daysAgo(8),
    currentAllocation: {
      id: 'alloc-21',
      spotId: 'spot-21',
      apartment: '401',
      block: 'Bloco C',
      residentName: 'Renata Vasconcelos',
      residentPhone: '(11) 98901-2345',
      concessionType: 'vitalicio',
      startDate: daysAgo(90),
      bicycle: {
        brandModel: 'Sense Move Urbana',
        color: 'Rosa Quartz',
        category: 'Urbana',
        tagNumber: 'TAG-2024-041',
      },
      photoUrl: SAMPLE_BIKE_PHOTOS[3],
      allocatedAt: daysAgo(90),
    },
  },
  {
    id: 'spot-22',
    spotNumber: 'S-22',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 6,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S22',
    // DISPONÍVEL
  },
  {
    id: 'spot-23',
    spotNumber: 'S-23',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 7,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S23',
    // DISPONÍVEL
  },
  {
    id: 'spot-24',
    spotNumber: 'S-24',
    sector: 'Setor C - Trilho Suspenso Leste',
    wallPosition: 8,
    maxWeightKg: 32,
    hookType: 'Gancho Teto Suspenso',
    qrCodeValue: 'COND-BIKE-S24',
    // DISPONÍVEL
  },
];

export const INITIAL_LOGS: UsageLog[] = [
  {
    id: 'log-1',
    spotId: 'spot-01',
    spotNumber: 'S-01',
    apartment: '402 (Bloco A)',
    residentName: 'Carlos Eduardo Mendes',
    type: 'check_in_uso',
    timestamp: daysAgo(2),
    method: 'qr_code',
    notes: 'Retirada e devolução registrada via escaneamento do QR Code da vaga S-01',
  },
  {
    id: 'log-2',
    spotId: 'spot-05',
    spotNumber: 'S-05',
    apartment: '301 (Bloco C)',
    residentName: 'Mariana Duarte Souza',
    type: 'check_in_uso',
    timestamp: daysAgo(1),
    method: 'qr_code',
    notes: 'Registro de uso diário (ida ao trabalho)',
  },
  {
    id: 'log-3',
    spotId: 'spot-17',
    spotNumber: 'S-17',
    apartment: '702 (Bloco B)',
    residentName: 'Patrícia Nogueira',
    type: 'alocacao',
    timestamp: daysAgo(15),
    method: 'painel_admin',
    notes: 'Nova concessão de vaga por tempo determinado (12 meses)',
  },
  {
    id: 'log-4',
    spotId: 'spot-02',
    spotNumber: 'S-02',
    apartment: '105 (Bloco B)',
    residentName: 'Fernanda Lima Rocha',
    type: 'notificacao_reporte',
    timestamp: daysAgo(10),
    method: 'painel_admin',
    notes: 'Notificação preventiva enviada ao morador sobre atualização cadastral',
  },
  {
    id: 'log-5',
    spotId: 'spot-09',
    spotNumber: 'S-09',
    apartment: '1202 (Bloco A)',
    residentName: 'Beatriz Martins Ramos',
    type: 'check_in_uso',
    timestamp: daysAgo(3),
    method: 'qr_code',
    notes: 'Check-in de uso para treino matinal',
  },
  {
    id: 'log-6',
    spotId: 'spot-12',
    spotNumber: 'S-12',
    apartment: '501 (Bloco A)',
    residentName: 'Juliana Costa e Silva',
    type: 'check_in_uso',
    timestamp: daysAgo(7),
    method: 'totem_portaria',
    notes: 'Registro de liberação na portaria',
  },
];
